In [3]:
import numpy as np

## Arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dementional arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
n[0,1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[2] = [1,1,1]

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [20]:
n[:,1]

array([20,  5,  1])

In [21]:
n[:,2] = [1,0,1]

In [22]:
n

array([[ 1, 20,  1],
       [ 4,  5,  0],
       [ 1,  1,  1]])

## Randomly generated arrays

In [23]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
a + 1

array([1, 2, 3, 4, 5])

In [28]:
a * 2

array([0, 2, 4, 6, 8])

In [29]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [30]:
b = (10 + (a * 2)) ** 2 / 100

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [33]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

## Comparison operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a > b

array([False, False,  True,  True,  True])

In [38]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [39]:
a

array([0, 1, 2, 3, 4])

In [41]:
a.std()

np.float64(1.4142135623730951)

In [42]:
n.min()

np.int64(0)